import type { NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";

const Index: NextPage = () => {
    const crypto = require('crypto'); // Importa el módulo crypto
    const publicKey = '827f8b5b9cb886ba9de29fe556014e64';
    const privateKey = 'f25221acbf7648af994ffc706f10dfa54b93fa0d';
    const timestamp = 1//Math.floor(new Date().getTime() / 1000); // Marca de tiempo en segundos

    // Concatena la clave pública, el timestamp y la clave privada
    const input = `${timestamp}${privateKey}${publicKey}`;
    // Calcula el hash MD5
    const hash = crypto.createHash('md5').update(input).digest('hex');

    console.log(hash); // Imprime el hash

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BodySingle title={"Sample"}>




            </BodySingle>
        </>
    )
}

export default Index
